# Generated by Django 5.1.2 on 2024-10-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('decription', models.TextField(max_length=100)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
